# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20160918_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosstrain',
            old_name='time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='rep',
            old_name='time',
            new_name='duration',
        ),
    ]
