# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20160921_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalrun',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
