# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20160921_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
