# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_activity_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='act_type',
            field=models.CharField(default=b'NormalRun', max_length=20),
        ),
        migrations.AddField(
            model_name='rep',
            name='rest',
            field=models.DurationField(default=datetime.timedelta(0, 1234)),
        ),
    ]
