# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20160922_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='goal_pace',
            field=models.FloatField(null=True),
        ),
    ]
