# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20160922_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalrun',
            name='cd_units',
            field=models.CharField(choices=[(b'Miles', b'Miles'), (b'Meters', b'Meters'), (b'Kilometers', b'Kilometers')], default=b'Miles', max_length=12),
        ),
        migrations.AddField(
            model_name='intervalrun',
            name='wu_units',
            field=models.CharField(choices=[(b'Miles', b'Miles'), (b'Meters', b'Meters'), (b'Kilometers', b'Kilometers')], default=b'Miles', max_length=12),
        ),
    ]
