# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20160922_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='team',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ManyToManyField(to='log.Team'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='season',
            field=models.ManyToManyField(to='log.Season'),
        ),
    ]
