# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20160928_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sport',
            field=models.CharField(choices=[(b'Indoor Track and Field', b'ITF'), (b'Outdoor Track and Field', b'OTF'), (b'Cross Country', b'XC')], default='XC', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
