# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20161002_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalrun',
            name='total_distance',
            field=models.FloatField(null=True),
        ),
    ]
