# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0015_auto_20161002_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(default=94, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
