# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_comment_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervalrun',
            old_name='total_distance',
            new_name='distance',
        ),
    ]
