# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 17:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0018_auto_20161015_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.SlugField()),
                ('token', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='sport',
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[(b'Indoor Track and Field', b'ITF'), (b'Outdoor Track and Field', b'OTF'), (b'Cross Country', b'XC')], default=b'Indoor Track and Field', max_length=3),
        ),
    ]
