# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0019_auto_20161017_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(to='log.Season'),
        ),
    ]
