# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0020_auto_20161017_2119'),
        ('log', '0019_intervalrun_units'),
    ]

    operations = [
    ]
