# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0021_merge_20161018_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
