# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0022_auto_20161018_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='season',
            new_name='seasons',
        ),
    ]
