# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0023_auto_20161019_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='log_private',
            field=models.BooleanField(default=True),
        ),
    ]
