# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0025_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pace',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='normalrun',
            name='pace',
            field=models.DurationField(null=True),
        ),
    ]
