# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0027_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='posted_date',
            field=models.DateField(default=datetime.date(2016, 11, 5)),
            preserve_default=False,
        ),
    ]
