# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0028_announcement_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='default_location',
            field=models.CharField(default='Kirkland, NY', max_length=50),
            preserve_default=False,
        ),
    ]
