# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0029_athlete_default_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user_label',
            field=models.CharField(default=b'Normal Run', max_length=35),
        ),
    ]
