# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0032_auto_20161115_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Shoe'),
        ),
    ]
