# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0034_shoe_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
