# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0035_shoe_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='starting_mileage',
            field=models.IntegerField(default=0),
        ),
    ]
