# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_shoe_starting_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='rest',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
