# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0037_auto_20161122_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='private_comments',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
