# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0039_athlete_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cd_units',
            field=models.CharField(choices=[(b'Miles', b'Miles'), (b'Meters', b'Meters'), (b'Kilometers', b'Kilometers')], default=b'Miles', max_length=12),
        ),
        migrations.AddField(
            model_name='activity',
            name='cooldown',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='gender',
            field=models.CharField(default=b'M', max_length=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='meet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Meet'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pace',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='units',
            field=models.CharField(choices=[(b'Miles', b'Miles'), (b'Meters', b'Meters'), (b'Kilometers', b'Kilometers')], default=b'Miles', max_length=12),
        ),
        migrations.AddField(
            model_name='activity',
            name='warmup',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='wu_units',
            field=models.CharField(choices=[(b'Miles', b'Miles'), (b'Meters', b'Meters'), (b'Kilometers', b'Kilometers')], default=b'Miles', max_length=12),
        ),
        migrations.AddField(
            model_name='rep',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rep',
            name='interval_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.IntervalRun'),
        ),
    ]
