# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0041_auto_20161225_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='gender',
            field=models.CharField(default=b'M', max_length=10),
        ),
    ]
